CREATE DATABASE IF NOT EXISTS gcan CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gcan;

CREATE TABLE IF NOT EXISTS categories (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(191) NOT NULL UNIQUE,
  description TEXT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS companies (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  whatsapp VARCHAR(32) NOT NULL,
  address VARCHAR(255) NOT NULL,
  logo TEXT NULL,
  instagram VARCHAR(191) NULL,
  approved TINYINT(1) NOT NULL DEFAULT 1,
  facebook VARCHAR(255) NULL,
  youtube VARCHAR(255) NULL,
  website VARCHAR(255) NULL,
  categoryId CHAR(36) NOT NULL,
  email VARCHAR(191) NULL,
  password VARCHAR(255) NULL,
  planId CHAR(36) NULL,
  description VARCHAR(300) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_companies_category (categoryId),
  INDEX idx_companies_approved (approved),
  CONSTRAINT fk_companies_category FOREIGN KEY (categoryId) REFERENCES categories(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ratings (
  id CHAR(36) PRIMARY KEY,
  stars SMALLINT NOT NULL,
  companyId CHAR(36) NOT NULL,
  userId CHAR(36) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ratings_company (companyId),
  CONSTRAINT fk_ratings_company FOREIGN KEY (companyId) REFERENCES companies(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(191) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(191) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plans (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  features JSON NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
